version: '3'


vars:
  # renovate: github=golangci/golangci-lint
  GO_LINT_CI_VERSION: v2.10.1

tasks:
  air:
    desc: Build local function
    cmd: 
      air

  render:
    desc: Run the examples against our local build
    dir: example
    cmd: crossplane render xr.yaml composition.yaml functions.yaml -e .

  lint:
    desc: Lint 
    cmd: go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GO_LINT_CI_VERSION}} -c .golangci.yml run ./...

  fmt:
    desc: fmt 
    cmd: |
      go fmt ./...
      go run github.com/daixiang0/gci@latest write .
      go run mvdan.cc/gofumpt@latest -l -w .
      go run golang.org/x/tools/cmd/goimports@latest -l -w .
      go run github.com/bombsimon/wsl/v4/cmd...@latest -strict-append -test=true -fix ./...
      go run github.com/catenacyber/perfsprint@latest -fix ./...
      go run github.com/tetafro/godot/cmd/godot@latest -w .
      go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GO_LINT_CI_VERSION}} -c .golangci.yml run ./... --fix
